version: 1.0.{build}
image: Ubuntu1804
init:
- sh: >-
    nvm install 10.15.2

    npm install -g yarn

    pip install --user --upgrade pip
clone_script:
- sh: git clone --recursive https://github.com/CFPAOrg/Modpack-GuideBook-i18n
install:
- sh: >-
    cd Modpack-GuideBook-i18n

    pip install --user -r requirements.txt

    cd page

    yarn
build_script:
- sh: >-
    cd ..

    python3 main.py

    cd page

    yarn build
test: off
deploy_script:
- sh: >-
    cd dist

    ls

    git config --global user.email "baka943@baka943.com"

    git config --global user.name "baka943"

    git init

    git add .

    git commit -m 'AppVeyor自动部署 '

    git push --force --quiet "https://baka943:${CO_TOKEN}@${CO_REF}" master:master