# 整合汉化补丁页面脚本配置文件
# 2019-03-30

# 需要转换成 utf-8 编码的文件
# 书写均为带反斜杠转义的正则表达式
# 正则匹配的文件，均应当为 GBK 编码
file_rgx:
 - "config/SimpleAchievements/achievementList\\.txt"
 - "SevTech Ages/.*?config/triumph/.*?\\.txt"

# data.json 文件的路径
data_json_path: "./page/static/data.json"
